name: "Setup poetry"
description: "Setup poetry for this environment. If possible, gets the dependencies from the cache."

runs:
  using: "composite"
  steps:
    - name: Install poetry
      shell: bash
      run: pip install poetry

    - id: cache-poetry
      name: Cache poetry dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      if: steps.cache-poetry.outputs.cache-hit != 'true'
      shell: bash
      run: poetry install --no-root
